-- MySQL Script generated by MySQL Workbench
-- Thu Nov  2 20:11:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SkyVault
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SkyVault
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SkyVault` DEFAULT CHARACTER SET utf8 ;
USE `SkyVault` ;

-- -----------------------------------------------------
-- Table `SkyVault`.`Airline`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkyVault`.`Airline` ;

CREATE TABLE IF NOT EXISTS `SkyVault`.`Airline` (
  `AirlineName` VARCHAR(35) NOT NULL,
  `numPlanes` INT NOT NULL DEFAULT 0,
  `type` VARCHAR(8) NULL,
  `logo` BLOB(35) NULL,
  PRIMARY KEY (`AirlineName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkyVault`.`Airport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkyVault`.`Airport` ;

CREATE TABLE IF NOT EXISTS `SkyVault`.`Airport` (
  `airportCode` LINESTRING NOT NULL,
  `location` VARCHAR(30) NOT NULL,
  `terminal` INT NOT NULL,
  `gate` INT NOT NULL,
  `runway` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`airportCode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkyVault`.`Airplane`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkyVault`.`Airplane` ;

CREATE TABLE IF NOT EXISTS `SkyVault`.`Airplane` (
  `RegistrationNum` INT NOT NULL,
  `gateNum` INT NOT NULL,
  `capacity` INT NOT NULL,
  `range` FLOAT NOT NULL,
  `year` INT NOT NULL,
  `type` LINESTRING NOT NULL,
  `license` INT NOT NULL,
  `routeNum` INT NOT NULL,
  `airlineNane` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`RegistrationNum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkyVault`.`Route`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkyVault`.`Route` ;

CREATE TABLE IF NOT EXISTS `SkyVault`.`Route` (
  `RouteNum` INT NOT NULL,
  `depart` DATETIME NOT NULL,
  `arrive` DATETIME NOT NULL,
  `duration` DATETIME NOT NULL,
  `DepartLocation` LINESTRING NULL,
  `ArrivalLocation` LINESTRING NULL,
  PRIMARY KEY (`RouteNum`),
  INDEX `ariportCode_idx` (`DepartLocation` ASC) VISIBLE,
  INDEX `ArrivalCode_idx` (`ArrivalLocation` ASC) VISIBLE,
  CONSTRAINT `DepartCode`
    FOREIGN KEY (`DepartLocation`)
    REFERENCES `SkyVault`.`Airport` (`airportCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ArrivalCode`
    FOREIGN KEY (`ArrivalLocation`)
    REFERENCES `SkyVault`.`Airport` (`airportCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkyVault`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkyVault`.`Person` ;

CREATE TABLE IF NOT EXISTS `SkyVault`.`Person` (
  `SSN` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`SSN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkyVault`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkyVault`.`Customer` ;

CREATE TABLE IF NOT EXISTS `SkyVault`.`Customer` (
  `SSN` VARCHAR(11) NOT NULL,
  `paymentMethod` LINESTRING NOT NULL,
  PRIMARY KEY (`SSN`),
  CONSTRAINT `C_SSN`
    FOREIGN KEY (`SSN`)
    REFERENCES `SkyVault`.`Person` (`SSN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkyVault`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkyVault`.`Employee` ;

CREATE TABLE IF NOT EXISTS `SkyVault`.`Employee` (
  `SSN` VARCHAR(11) NOT NULL,
  `salary` FLOAT NOT NULL,
  `time` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`SSN`),
  CONSTRAINT `E_SSN`
    FOREIGN KEY (`SSN`)
    REFERENCES `SkyVault`.`Person` (`SSN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkyVault`.`Seat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkyVault`.`Seat` ;

CREATE TABLE IF NOT EXISTS `SkyVault`.`Seat` (
  `seatNum` INT NOT NULL,
  `window` INT NULL,
  `aisle` INT NULL,
  `exit` INT NULL,
  `registrationNum` VARCHAR(45) NULL,
  PRIMARY KEY (`seatNum`),
  CONSTRAINT `registrationNum`
    FOREIGN KEY (`seatNum`)
    REFERENCES `SkyVault`.`Airplane` (`RegistrationNum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkyVault`.`Crew`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkyVault`.`Crew` ;

CREATE TABLE IF NOT EXISTS `SkyVault`.`Crew` (
  `C_license` INT NOT NULL,
  `C_location` VARCHAR(30) NOT NULL,
  `size` FLOAT NOT NULL,
  `salary` FLOAT NOT NULL,
  `airlineName` VARCHAR(45) NULL,
  PRIMARY KEY (`C_license`),
  INDEX `AirlineName_idx` (`airlineName` ASC) VISIBLE,
  CONSTRAINT `CR_AirlineName`
    FOREIGN KEY (`airlineName`)
    REFERENCES `SkyVault`.`Airline` (`AirlineName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkyVault`.`Pilot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkyVault`.`Pilot` ;

CREATE TABLE IF NOT EXISTS `SkyVault`.`Pilot` (
  `SSN` VARCHAR(11) NOT NULL,
  `pilotLicense(30)` VARCHAR(30) NOT NULL,
  `experience` INT NOT NULL,
  `age` INT NOT NULL,
  `license` INT NOT NULL,
  PRIMARY KEY (`SSN`),
  INDEX `license_idx` (`license` ASC) VISIBLE,
  CONSTRAINT `P_SSN`
    FOREIGN KEY (`SSN`)
    REFERENCES `SkyVault`.`Person` (`SSN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `license`
    FOREIGN KEY (`license`)
    REFERENCES `SkyVault`.`Crew` (`C_license`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkyVault`.`Flight Attendant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkyVault`.`Flight Attendant` ;

CREATE TABLE IF NOT EXISTS `SkyVault`.`Flight Attendant` (
  `SSN` VARCHAR(11) NOT NULL,
  `experience` VARCHAR(30) NOT NULL,
  `license` INT NOT NULL,
  PRIMARY KEY (`SSN`),
  INDEX `F_license_idx` (`license` ASC) VISIBLE,
  CONSTRAINT `F_SSN`
    FOREIGN KEY (`SSN`)
    REFERENCES `SkyVault`.`Person` (`SSN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `F_license`
    FOREIGN KEY (`license`)
    REFERENCES `SkyVault`.`Crew` (`C_license`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkyVault`.`Terminal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkyVault`.`Terminal` ;

CREATE TABLE IF NOT EXISTS `SkyVault`.`Terminal` (
  `terminalLetter` VARCHAR(1) NOT NULL,
  `gateAmount` INT NOT NULL,
  `airportCode` LINESTRING NOT NULL,
  PRIMARY KEY (`terminalLetter`),
  INDEX `airportCode_idx` (`airportCode` ASC) VISIBLE,
  CONSTRAINT `T_airportCode`
    FOREIGN KEY (`airportCode`)
    REFERENCES `SkyVault`.`Airport` (`airportCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkyVault`.`Gate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkyVault`.`Gate` ;

CREATE TABLE IF NOT EXISTS `SkyVault`.`Gate` (
  `gateNum` INT NOT NULL,
  `teminalLetter` VARCHAR(1) NOT NULL,
  `registrationNum` INT NOT NULL,
  `airportCode` LINESTRING NOT NULL,
  PRIMARY KEY (`gateNum`),
  INDEX `terminalLetter_idx` (`teminalLetter` ASC) VISIBLE,
  INDEX `registrationNum_idx` (`registrationNum` ASC) VISIBLE,
  INDEX `airportCode_idx` (`airportCode` ASC) VISIBLE,
  CONSTRAINT `terminalLetter`
    FOREIGN KEY (`teminalLetter`)
    REFERENCES `SkyVault`.`Terminal` (`terminalLetter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `registrationNum`
    FOREIGN KEY (`registrationNum`)
    REFERENCES `SkyVault`.`Airplane` (`RegistrationNum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `G_airportCode`
    FOREIGN KEY (`airportCode`)
    REFERENCES `SkyVault`.`Airport` (`airportCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkyVault`.`Ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkyVault`.`Ticket` ;

CREATE TABLE IF NOT EXISTS `SkyVault`.`Ticket` (
  `ticketNum` INT NOT NULL,
  `routeNum` VARCHAR(60) NOT NULL,
  `class` VARCHAR(20) NOT NULL,
  `price` FLOAT NOT NULL,
  `seatNum` INT NOT NULL,
  `SSN` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ticketNum`),
  INDEX `seatNum_idx` (`seatNum` ASC) VISIBLE,
  INDEX `SSN_idx` (`SSN` ASC) VISIBLE,
  CONSTRAINT `seatNum`
    FOREIGN KEY (`seatNum`)
    REFERENCES `SkyVault`.`Seat` (`seatNum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `T_SSN`
    FOREIGN KEY (`SSN`)
    REFERENCES `SkyVault`.`Customer` (`SSN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
